export enum SplitModelEnum {
  'Equal Split' = 'EQUAL_SPLIT',
  'Customized' = 'CUSTOMIZED',
  'Define Later' = 'DEFINE_LATER',
}

export enum TypeCollaboratorEnum {
  'Single' = 'SINGLE',
  'Album' = 'ALBUM',
}

export enum PermissionProjectEnum {
  // 'Owner' = 'OWNER',
  // 'Editor' = 'EDITOR',
  // 'Musician' = 'MUSICIAN',
  // 'Producer' = 'PRODUCER',
  // 'View Only' = 'VIEW_ONLY',


  'Owner' = 'OWNER',
  'Upload/Download' = 'UPLOAD/DOWNLOAD',
  'Upload Only' = 'UPLOAD_ONLY',
  'Download Only' = 'DOWNLOAD_ONLY',
  'View Only' = 'VIEW_ONLY',
}

export enum ExceptionsEnum {
  NotFound = 'NotFound',
  BadRequest = 'BadRequest',
  Unauthorized = 'Unauthorized',
  Forbidden = 'Forbidden',
  InternalServerError = 'InternalServerError',
  UnprocessableEntity = 'UnprocessableEntity',
  Conflict = 'Conflict',
}

export enum ExceptionStatus {
  NotFound = 404,
  BadRequest = 400,
  Unauthorized = 401,
  Forbidden = 403,
  InternalServerError = 500,
  UnprocessableEntity = 422,
  Conflict = 409,
}

export enum ProjectUpdateEnum {
  'ADDED_FILES_TO_RELEASE' = 'ADDED_FILES_TO_RELEASE',
  'REMOVED_FILES_FROM_RELEASE' = 'REMOVED_FILES_FROM_RELEASE',
  'ADDED_FILES_TO_MAIN_FOLDER' = 'ADDED_FILES_TO_MAIN_FOLDER',
  'UNLINKED_FILES_FROM_MAIN_FOLDER' = 'UNLINKED_FILES_FROM_MAIN_FOLDER',
  'ADDED_FILES_TO_FINAL_VERSION' = 'ADDED_FILES_TO_FINAL_VERSION',
  'REMOVED_FILES_FROM_FINAL_VERSION' = 'REMOVED_FILES_FROM_FINAL_VERSION',
  'CREATED_RELEASE' = 'CREATED_RELEASE',
  'RENAMED_RELEASE' = 'RENAMED_RELEASE',
  'PUBLISHED_RELEASE' = 'PUBLISHED_RELEASE',
  'COMMENT' = 'COMMENT',
  'CREATED_PROJECT' = 'CREATED_PROJECT',
  'RENAMED_PROJECT' = 'RENAMED_PROJECT',
  'MINTED_NFTS' = 'MINTED_NFTS',
}

export enum NotifyTypeEnum {
  ADD_COLLABORATOR = 'ADD_COLLABORATOR',
  REMOVE_COLLABORATOR = 'REMOVE_COLLABORATOR',
  CHAT = 'CHAT_MESSAGE',
  CALL = 'CALL_REQUEST',
  ADDED_TRACKS_TO_RELEASE = 'ADDED_TRACKS_TO_RELEASE',
  ADDED_TRACKS_TO_MAIN_FOLDER = 'ADDED_TRACKS_TO_PROJECT',
  REMOVED_TRACKS_FROM_RELEASE = 'REMOVED_TRACKS_FROM_RELEASE',
  ADDED_TRACKS_TO_FINAL_VERSION = 'ADDED_TRACKS_TO_FINAL_VERSION',
  REMOVED_TRACKS_FROM_FINAL_VERSION = 'REMOVED_TRACKS_FROM_FINAL_VERSION',
  COMMENTED_ON_PROJECT = 'COMMENTED_ON_PROJECT',
  USER_FOLLOWED_YOU = 'USER_FOLLOWED_YOU',
  UPDATED_RELEASE_SPLITS = 'UPDATED_RELEASE_SPLITS',
  USER_ANSWERED_CONTRACT_SPLIT = 'USER_ANSWERED_CONTRACT_SPLIT',
  USER_REACTED_TO_ACTIVITY = 'USER_REACTED_TO_ACTIVITY',
  USER_COMMENTED_ON_ACTIVITY = 'USER_COMMENTED_ON_ACTIVITY',
  COMMENTED_ON_TRACK = 'COMMENTED_ON_TRACK',
  COLLABORATOR_ADDED = 'COLLABORATOR_ADDED',
  COLLABORATOR_REQ = 'COLLABORATOR_REQ',
  ACCEPT_INVITATION = 'ACCEPT_INVITATION',
  PUBLIC_STREAM = 'PUBLIC_STREAM',
  PRIVATE_STREAM = 'PRIVATE_STREAM',
  NFT_BUY = 'NFT_BUY',
  NFT_EXCHANGE_APPROVED = 'NFT_EXCHANGE_APPROVED',
  GAMIFICATION_TOKENS = 'GAMIFICATION_TOKENS',
  MISSION_COMPLETED = 'MISSION_COMPLETED',
  MISSION_PERFORMED = 'MISSION_PERFORMED',
}

export enum AndroidNotificationImportanceEnum {
  UNKNOWN,
  UNSPECIFIED,
  NONE,
  MIN,
  LOW,
  DEFAULT,
  HIGH,
  MAX,
}

export enum StorageType {
  IPFS = 'ipfs',
  GC = 'gc',
  S3 = 's3',
}

export enum CollaborateWithEnum {
  FANS = 'FANS',
  ARTIST = 'ARTISTS',
}

export enum CollaborationTypeEnum {
  SONG_CONTEST = 'SONG_CONTEST',
  ART_AND_DESIGN = 'ART_AND_DESIGN',
  OTHER = 'OTHERS',
}
