import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import { ObjectId } from 'mongodb';

import {
  IsNotEmpty,
  IsString,
  IsNumber,
  IsArray,
  IsOptional,
  IsUrl,
  IsBoolean,
} from 'class-validator';

export class createTrackInitialDto {
  // Required props
  @ApiProperty({
    description: 'The name of the track',
  })
  @IsNotEmpty()
  @IsString()
  name: string;

  @ApiPropertyOptional({
    description: 'The folder ID',
  })
  @IsOptional()
  @IsString()
  folder_id: string;

  @ApiPropertyOptional({
    description: 'The track project ID',
  })
  @IsOptional()
  @IsString()
  project_id: string;

  @ApiPropertyOptional({
    description: 'The track instruments IDs',
  })
  @IsOptional()
  @IsArray()
  instrument: [string];

  @ApiPropertyOptional({
    description: 'The track genres IDs',
  })
  @IsOptional()
  @IsArray()
  genre: [string];

  @ApiPropertyOptional({
    description: 'The track tags IDs',
  })
  @IsOptional()
  @IsArray()
  tags: [string];

  @ApiPropertyOptional({
    description: 'The track size',
  })
  @IsOptional()
  @IsNumber()
  size: number;

  @ApiPropertyOptional({
    description: 'The track duration',
  })
  @IsOptional()
  @IsNumber()
  duration: number;

  @ApiPropertyOptional({
    description: 'The track channels',
  })
  @IsOptional()
  @IsNumber()
  channels: number;

  @ApiPropertyOptional({
    description: 'The track sample rate',
  })
  @IsOptional()
  @IsNumber()
  rate: number;

  @ApiPropertyOptional({
    description: 'The track bitrate',
  })
  @IsOptional()
  @IsNumber()
  bitrate: number;

  @ApiPropertyOptional({
    description: 'The track bpm',
  })
  @IsOptional()
  @IsNumber()
  BPM: number;

  @ApiPropertyOptional({
    description: 'The video resolution',
  })
  @IsOptional()
  @IsNumber()
  resolution: number;

  @ApiPropertyOptional({
    description: 'The track version',
  })
  @IsOptional()
  @IsNumber()
  version: number;

  @ApiPropertyOptional({
    description: 'The track URL',
  })
  @IsOptional()
  @IsString()
  @IsUrl()
  url: string;

  @ApiPropertyOptional({
    description:
      'The token. Necessary for tracks stored on providers like Google Drive',
  })
  @IsOptional()
  @IsString()
  driveToken?: string;

  @ApiProperty({ required: false })
  @IsOptional()
  @IsString()
  artworkUrl?: string;

  @ApiPropertyOptional({
    description: 'If track recorded by mobile.',
    type: Boolean,
  })
  @IsOptional()
  @Transform(({ value }) => value === 'true' || value === true)
  @IsBoolean()
  isMobileRecorded: boolean;

  @ApiPropertyOptional({
    description: 'If track generated by AI.',
    type: Boolean,
  })
  @IsOptional()
  @Transform(({ value }) => value === 'true' || value === true)
  @IsBoolean()
  isAIGenerated: boolean;

  @IsString()
  _id: string | ObjectId;

  @IsOptional()
  @IsString()
  fileSize: string;

  @IsOptional()
  @IsString()
  extension?: 'wav' | 'mp3' | 'm4a' | 'mp4' | 'avi' | 'zip' | 'ptx';

}
